routes/web.php
<?php

Auth::routes(['register' => false]);

Route::get('/crudIndex', 'HomeController@crudIndex');
Route::get('/crud2index', 'HomeController@crud2index');
Route::post('/jsonSave', 'HomeController@jsonSave');
Route::post('/crudMaker', 'HomeController@crudMaker');
//------------------------------------------------------------

Route::group(['middleware' => ['auth']], function () {
    // Route::get('/', 'HomeController@index');
    Route::get('/sidebar', 'HomeController@sidebar');
    Route::get('/sidebar/show', 'HomeController@sidebarShow');
    Route::get('/dashboard', 'HomeController@index');

    // Route::resource('admin/school', 'Admin\\SchoolController');
    Route::get('admin/settings', 'Admin\\RoleSettingsContoller@show');
    Route::post('admin/settings/{id}', 'Admin\\RoleSettingsContoller@update');

    Route::resource('admin/holiday', 'Admin\\HolidayController');
    Route::resource('admin/slider', 'Admin\\SliderController');
    Route::resource('admin/service', 'Admin\\ServiceController');
    Route::resource('admin/objective', 'Admin\\ObjectiveController');
    Route::resource('admin/category', 'Admin\\CategoryController');
    Route::resource('admin/project', 'Admin\\ProjectController');
    Route::resource('admin/our_team', 'Admin\\OurTeamController');
    Route::resource('admin/message', 'Admin\\MessageController');
    Route::resource('admin/contact', 'Admin\\ContactController');
    Route::resource('admin/about', 'Admin\\AboutController');
    Route::resource('admin/client', 'Admin\\ClientController');
    Route::resource('admin/newsletter', 'Admin\\NewsletterController');
    Route::resource('admin/blog-category', 'Admin\\BlogCategoryController');
    Route::resource('admin/blog', 'Admin\\BlogController');
    // Route::get('admin/theme', 'HomeController@themes');

    //------------------------------------------------------ Student management System-------------------------------------------------




});

    Route::get('/', 'FrontEndController@home');
    Route::get('/service-details/{slug}', 'FrontEndController@serviceDetails');
    Route::get('/project-details/{slug}', 'FrontEndController@projectDetails');
    Route::get('/projects', 'FrontEndController@projects');
    Route::get('/services', 'FrontEndController@services');
    Route::get('/team', 'FrontEndController@team');
    Route::get('/clients', 'FrontEndController@clients');
    Route::get('/about', 'FrontEndController@about');
    Route::get('/blog', 'FrontEndController@blog');
    Route::get('/blog/{slug}', 'FrontEndController@slugBlog');
    Route::get('/blog_single/{slug}', 'FrontEndController@blog_single');
    Route::get('/contacts', 'FrontEndController@contacts');
    Route::post('/message', 'FrontEndController@addMessage');
    Route::post('/newsletter', 'FrontEndController@addEmail');

    

Route::get('/live', function () {
    return view('frontEnd.live');
    
});

resources/views/crud.blade.php
@extends('layouts.app',['pageTitle' => __('Crud 1')])
@section('content')

@component('layouts.parts.breadcrumb')
    @slot('title')
        {{ __('Crud 1') }}
    @endslot
@endcomponent
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Crud Generate</div>

                <div class="card-body">
                    <form action="{{ url('crudMaker') }}" method="post">
                        @csrf
                    <input type="text" class="form-control" id="modelName" name="modelName" placeholder="Model Name">
                    
                    <div class="form-inline m-1" style="padding: 10px">
                        
                        <input type="text"  class="form-control"  id="name" placeholder="name">
                        
                        {{-- <input type="text" class="form-control" id="type" placeholder="type"> --}}
                        <select name="type" id="type" class="form-control">
                            <option value="string">string</option>
                            <option value="email">email</option>
                            <option value="integer">integer</option>
                            <option value="textarea">textarea</option>
                            <option value="number">number</option>
                            <option value="date">date</option>
                            <option value="time">time</option>
                            <option value="file">file</option>
                            <option value="password">password</option>
                            <option value="integer#unsigned">integer#unsigned</option>
                        </select>
                        <a href="#" class="btn btn-success btn-sm add-row "><i class="fa fa-plus" aria-hidden="true"></i></a>
                    </div>
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Select</th>
                                <th>Type</th>
                                <th>Name</th>
                                <th>Result</th>
                            </tr>
                        </thead>
                        <tbody>
                            
                        </tbody>
                    </table>
                    <button type="button" class="delete-row btn btn-danger btn-sm"> <i class="fa fa-trash" aria-hidden="true"></i> </button>
                    <button type="submit" class="btn btn-success">Submit</button>
                </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('js')
<script>
    $(document).ready(function(){
        var i = 0;
        var totalString ='';

        $(".add-row").click(function(e){
                e.preventDefault();
            var type = $("#type").val();
            var name = $("#name").val();
            if (type != '' && name != '') {
                var hash = "#";
                var res = name+hash+type+';';
                totalString += res;
                $('#totalString').val(totalString);
                var markup = "<tr><td><input type='checkbox' name='record'></td><td>" + type + "</td><td>" + name + "</td> </td><td><input type='text' value='" + res + "'  id='fields' name='fields[]' style='border:unset;'></td></tr>";
                $("table tbody").append(markup);

            }
            // $("#type").val('');
            $("#name").val('');
        });
        
        // Find and remove selected table rows
        $(".delete-row").click(function(){
            $("table tbody").find('input[name="record"]').each(function(){
                if($(this).is(":checked")){
                    $(this).parents("tr").remove();
                }
            });
        });
    });    
</script>

@endpush
@push('css')
    <style>
    input {
        margin: 10px !important;
}
    </style>
@endpush

resources/views/crud2.blade.php
@extends('layouts.app',['pageTitle' => __('Crud 2')])
@section('content')

@component('layouts.parts.breadcrumb')
    @slot('title')
        {{ __('Crud 2') }}
    @endslot
@endcomponent
 
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="d-md-flex align-items-center">
                        <div>
                            <h4 class="card-title">Crud Generate</h4>
                            <h5 class="card-subtitle">System creater</h5>
                        </div>
                    </div>
                    @if ($message = Session::get('success'))
                    <div class="alert alert-success alert-block">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <strong>{{ $message }}</strong>
                    </div>
                    @endif
                    @if ($message = Session::get('error'))
                    <div class="alert alert-danger alert-block">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <strong>{{ $message }}</strong>
                    </div>
                    @endif
                    @if ($errors->any())
                    <div class="alert alert-danger alert-block">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        @foreach ($errors->all() as $error)
                            <strong>{{$error}}</strong>
                        @endforeach
                    </div>
                        
                    @endif

                    <form action="{{ url('jsonSave') }}" method="post">
                        @csrf
                        <input type="text" class="form-control" id="modelName" name="modelName"
                            placeholder="Model Name">

                        <div class="form-inline m-1" style="padding: 10px">
                            <input type="text" class="form-control" id="name" placeholder="field name">
                            <select name="type" id="type" class="form-control">
                                <option value="string">string</option>
                                {{-- <option value="email">email</option> --}}
                                <option value="integer">integer</option>
                                <option value="textarea">textarea</option>
                                <option value="number">number</option>
                                <option value="date">date</option>
                                <option value="time">time</option>
                                <option value="file">file</option>
                                <option value="password">password</option>
                                <option value="integer#unsigned">integer#unsigned</option>
                                <option value="bigint#unsigned">bigInteger#unsigned</option>
                            </select>

                            <select name="required" id="required" class="form-control">
                                <option value="not">Not required</option>
                                <option value="required">required</option>
                            </select>

                            <a href="#" style="margin-left: 5px" class="btn btn-success btn-sm add-row "><i class="fa fa-plus"
                                    aria-hidden="true"></i></a>
                            {{-- <input type="checkbox" name="" id="foreginKeyDivShow" > --}}
                            <div style="margin-left: 5px">
                                <input type="checkbox" id="foreginKeyDivShow">
                                <label for="foreginKeyDivShow"></label>
                            </div>
                            <div id="foreginKeyDiv">
                                <input type="text" class="form-control" id="referencesTable"
                                    placeholder="references table">
                                <input type="text" class="form-control" id="referencesField"
                                    placeholder="references field">
                            </div>
                        </div>
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>Select</th>
                                    <th>Type</th>
                                    <th>Name</th>
                                    <th>Required</th>
                                    <th>References table</th>
                                    <th>References field</th>
                                </tr>
                            </thead>
                            <tbody id="fieldTable">

                            </tbody>
                        </table>
                        <button type="button" class="delete-row btn btn-danger btn-sm"> <i class="fa fa-trash"
                                aria-hidden="true"></i> </button>

                        <hr>
                        <div class="form-inline m-1" style="padding: 10px">
                            <input type="text" class="form-control" id="rname" placeholder="function name">
                            <select id="rtype" class="form-control">
                                <option value="belongsTo">hasOne</option>
                                <option value="belongsTo">belongsTo</option>
                                <option value="hasManey">hasMany</option>
                            </select>

                            <input type="text" class="form-control" id="rclass" placeholder="App\class">

                            <a href="#" class="btn btn-success btn-sm " id="addReletionship"><i class="fa fa-plus"
                                    aria-hidden="true"></i></a>
                        </div>
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>Select</th>
                                    <th>RType</th>
                                    <th>RName</th>
                                    <th>class</th>
                                </tr>
                            </thead>
                            <tbody id="reletion">

                            </tbody>
                        </table>
                        <button type="button" class="delete-row btn btn-danger btn-sm"> <i class="fa fa-trash"
                                aria-hidden="true"></i> </button>
                        <button type="submit" class="btn btn-success">Submit</button>
                    </form>
                </div>
            </div>
        </div>
        

@endsection
@push('js')
<script>
    $(document).ready(function() {
        var i = 0;
        var totalString = '';
        $(".add-row").click(function(e) {
            e.preventDefault();
            var type = $("#type").val();
            var name = $("#name").val();
            var required = $("#required").val();
            var referencesTable = $("#referencesTable").val();
            var referencesField = $("#referencesField").val();
            if (type != '' && name != '') {
                var hash = "#";
                var res = name + hash + type + ';';
                totalString += res;
                $('#totalString').val(totalString);
                var markup =
                    "<tr><td class='align-center'><input type='checkbox' name='record'></td><td class='align-center'><input type='text' value='" +
                    type +
                    "'  id='type' name='type[]' style='width: 60px;border:unset;'></td><td class='align-center'><input type='text' value='" +
                    name +
                    "'  id='name' name='name[]' style='width: 60px;border:unset;'></td> </td><td class='align-center'><input type='text' value='" +
                    required +
                    "'  id='required' name='required[]' style='width: 60px;border:unset;'></td><td class='align-center'><input type='text' value='" +
                    referencesTable +
                    "'  id='required' name='referencesTable[]' style='width: 60px;border:unset;'></td><td class='align-center'><input type='text' value='" +
                    referencesField +
                    "'  id='required' name='referencesField[]' style='width: 60px;border:unset;'></td></tr>";
                $("#fieldTable").append(markup);
            }
            // $("#type").val('');
            $("#name").val('');
            // $("#required").val('');
            $("#referencesTable").val('');
            $("#referencesField").val('');
        });
        // Find and remove selected table rows
        $(".delete-row").click(function() {
            $("table tbody").find('input[name="record"]').each(function() {
                if ($(this).is(":checked")) {
                    $(this).parents("tr").remove();
                }
            });
        });
    });
    $('#addReletionship').click(function(e) {
        e.preventDefault();
        var rtype = $("#rtype").val();
        var rname = $("#rname").val();
        var rclass = $("#rclass").val();
        if (rtype != '' && rname != '' && rclass != '') {
        var rmarkup = "<tr><td><input type='checkbox' name='record'></td><td><input type='text' value='" +
            rtype +
            "'  id='type' name='rtype[]' style='border:unset;'></td><td><input type='text' value='" + rname +
            "'  id='name' name='rname[]' style='border:unset;'></td> </td></td><td><input type='text' value='" +
            rclass +
            "'  id='required' name='class[]' style='border:unset;'></td></tr>";
        $("#reletion").append(rmarkup);
        }
        $("#rname").val('');
        // $("#rtype").val('');
        $("#rclass").val('');

    });
    $("#foreginKeyDiv").hide();
    $("#foreginKeyDivShow").change(function(e) {
        e.preventDefault();
        // alert('click');
        if (this.checked) {
            $('#foreginKeyDiv').slideDown('show').show();
        } else {
            $("#foreginKeyDiv").slideUp("slow")
        }
    });
</script>

@endpush
@push('css')
<style>
    input {
        margin: 10px !important;
    }
</style>
@endpush

resources/views/dashboard.blade.php
@extends('layouts.app',['pageTitle' => __('Dashboard')])
@section('content')

@component('layouts.parts.breadcrumb')
    @slot('title')
        {{ __('Dashboard') }}
    @endslot
@endcomponent
<div class="row">
<div class="col-md-6">
    <div class="card">
        <div class="card-body">
            
            {{-- <div class="row">
                <div class="col">
                    <div class="card card-hover">
                        <div class="box bg-success text-center">
                            <h1 class="font-light text-white"><i class="fa fa-user "></i></h1>
                            <h5 class="m-b-0 m-t-5 text-white">{{Hr::coutTableRow('employees')}}</h5>
                            <small class="font-light text-white">Total Employee</small>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card card-hover">
                        <div class="box bg-warning text-center">
                            <h1 class="font-light text-white"><i class="mdi mdi-collage"></i></h1>
                            <h6 class="text-white">Attendance</h6>
                            <h5 class="m-b-0 m-t-5 text-white">{{Hr::coutTableRowDaly('attendances')->count()}}</h5>

                        </div>
                    </div>
                </div>

                <div class="col">
                    <div class="card card-hover">
                        <div class="box bg-info text-center">
                            <h1 class="font-light text-white"><i class="mdi mdi-collage"></i></h1>
                            <h6 class="text-white">Expense</h6>
                            <h5 class="m-b-0 m-t-5 text-white">{{Hr::coutTableRowDaly('expenses')->sum('amount')}}</h5>

                        </div>
                    </div>
                </div>
            </div> --}}
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            
            {{-- <div class="row">
                <div class="col">
                    <div class="card card-hover">
                            <img src="{{ asset('img/human_resources_management.jpeg') }}" alt="" srcset="" height="340px">
                    </div>
                </div>
            </div> --}}
        </div>
    </div>
</div>
<div class="col-md-6">
    <div class="card">
        <div class="card-body" style="min-width:200px">
            
            <div class="row">
                <div id="MyClockDisplay" class="clock" onload="showTime()"></div>
                <div id='calendar'></div>
            </div>

        </div>
    </div>
</div>
</div>
@endsection

@push('css')
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.1.0/fullcalendar.min.css' />
<style>
    .clock {
    /* position: absolute; */
    /* top: 50%; */
    left: 50%;
    /* transform: translateX(80%) translateY(0%); */
    color: #17D4FE;
    font-size: 30px;
    /* font-family: Orbitron;
    letter-spacing: 7px; */
   


}
</style>
@endpush

@push('js')
<script src='https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.1/moment.min.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.1.0/fullcalendar.min.js'></script>
<script>
    function showTime(){
    var date = new Date();
    var h = date.getHours(); // 0 - 23
    var m = date.getMinutes(); // 0 - 59
    var s = date.getSeconds(); // 0 - 59
    var session = "AM";
    
    if(h == 0){
        h = 12;
    }
    
    if(h > 12){
        h = h - 12;
        session = "PM";
    }
    
    h = (h < 10) ? "0" + h : h;
    m = (m < 10) ? "0" + m : m;
    s = (s < 10) ? "0" + s : s;
    
    var time = h + ":" + m + " " + session;
    document.getElementById("MyClockDisplay").innerText = time;
    document.getElementById("MyClockDisplay").textContent = time;
    
    setTimeout(showTime, 1000);
    
}
showTime();
</script>

<script>
    $(document).ready(function() {
        $('#calendar').fullCalendar({
            events : [
                @foreach(App\Holiday::all() as $holiday)
                {
                    title : '{{ $holiday->name }}',
                    start : '{{ $holiday->holiday_date }}',
                    url : '{{ route('holiday.edit', $holiday->id) }}'
                },
                @endforeach
            ]
        })
    });
</script>
@endpush